const LOGIN = "LOGIN";
const LOGIN_BEGIN="LOGIN_BEGIN";
const LOGIN_SUCCESS="LOGIN_SUCCESS";
const LOGIN_FAIL="LOGIN_FAIL";
const LOGOUT="LOGOUT";
const REGISTER_BEGIN="REGISTER_BEGIN";
const REGISTER_SUCCESS="REGISTER_SUCCESS";
const REGISTER_FAIL="REGISTER_FAIL";

module.exports={
    LOGIN, LOGIN_BEGIN,LOGIN_SUCCESS, LOGIN_FAIL, 
    LOGOUT,
    REGISTER_BEGIN, REGISTER_SUCCESS, REGISTER_FAIL};